// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeliculasMVC.Data;

#nullable disable

namespace PeliculasMVC.Migrations
{
    [DbContext(typeof(PeliculasMVCContext))]
    partial class PeliculasMVCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeliculasMVC.Models.Genero", b =>
                {
                    b.Property<int>("Id_Genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Genero"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Genero");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("PeliculasMVC.Models.Pelicula", b =>
                {
                    b.Property<int>("Id_Pelicula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Pelicula"));

                    b.Property<DateTime>("Fecha_Lanzamiento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Pelicula");

                    b.ToTable("Pelicula");
                });

            modelBuilder.Entity("PeliculasMVC.Models.PeliculaGenero", b =>
                {
                    b.Property<int>("Id_PeliculaGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_PeliculaGenero"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.HasKey("Id_PeliculaGenero");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("PeliculaGenero");
                });

            modelBuilder.Entity("PeliculasMVC.Models.PeliculaGenero", b =>
                {
                    b.HasOne("PeliculasMVC.Models.Genero", "Genero")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeliculasMVC.Models.Pelicula", "Pelicula")
                        .WithMany("PeliculaGenero")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("PeliculasMVC.Models.Genero", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("PeliculasMVC.Models.Pelicula", b =>
                {
                    b.Navigation("PeliculaGenero");
                });
#pragma warning restore 612, 618
        }
    }
}
